# Generated by Django 5.1.3 on 2025-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
