# Generated by Django 5.1.7 on 2025-03-23 07:48

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeusers', '0003_customuser_location_customuser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='profile_Pic'),
            preserve_default=False,
        ),
    ]
