# Generated by Django 5.1.7 on 2025-04-09 06:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeusers', '0004_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='../static/media/person.png', max_length=255, verbose_name='profile_Pic'),
        ),
    ]
