# Generated by Django 5.1.7 on 2025-04-14 17:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeusers', '0005_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pics/crcmmzrp6a5il1tdx7al', max_length=255, null=True, verbose_name='image'),
        ),
    ]
