# Generated by Django 5.1.7 on 2025-04-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvp_user_side', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
    ]
