# Generated by Django 5.1.7 on 2025-04-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvp_user_side', '0003_remove_feedback_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dvp_user_side.feedback')),
            ],
        ),
    ]
