# Generated by Django 5.1.3 on 2025-03-06 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('descriptiion', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='product_images')),
                ('image_2d', models.ImageField(blank=True, default='default/default.png', null=True, upload_to='2D_images')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'business'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_likes', models.PositiveIntegerField(default=0)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='homebase.products')),
            ],
        ),
    ]
