# Generated by Django 5.1.3 on 2025-03-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
