# Generated by Django 5.1.7 on 2025-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0002_rename_descriptiion_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.CharField(choices=[('kitchen', 'kitchen'), ('office', 'office'), ('living room', 'living room'), ('dining  room', 'dining room')], default='living room', max_length=20),
        ),
    ]
