# Generated by Django 5.1.7 on 2025-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0003_products_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
