# Generated by Django 5.1.7 on 2025-03-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0006_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
