# Generated by Django 5.1.7 on 2025-03-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0007_remove_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_2d',
        ),
    ]
