# Generated by Django 5.1.7 on 2025-03-22 07:27

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0008_remove_products_image_2d'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='bg_removed_image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='bg_removed_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='orignal_image'),
        ),
    ]
