# Generated by Django 5.1.7 on 2025-03-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0009_images_bg_removed_image_images_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='bg_removed_image',
            field=models.ImageField(blank=True, null=True, upload_to='bg-removed'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orignal_images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homebase.products'),
        ),
    ]
